# SERVER
server.port=${PORT:8080}
server.address=0.0.0.0

spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,\
org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration,\
org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration

# JWT
jwt.secret=${JWT_SECRET:defaultsecret123}
jwt.expiration=86400000

# ADMIN
admin.secret=${ADMIN_SECRET:defaultadmin123}

# GEMINI
gemini.api.key=${GEMINI_API_KEY:dummykey}

# MAIL
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# OTHER
spring.jackson.serialization.fail-on-empty-beans=false
app.production=true