# SERVER
server.port=${PORT:8080}
server.address=0.0.0.0

spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,\
org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration,\
org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration

# JWT
jwt.secret=${JWT_SECRET:defaultsecret123}
jwt.expiration=86400000

# ADMIN
admin.secret=${ADMIN_SECRET:defaultadmin123}

# GEMINI
gemini.api.key=${GEMINI_API_KEY:dummykey}

# OTHER
spring.jackson.serialization.fail-on-empty-beans=false
app.production=true